### ISSUE TITLE
Crashes with create

### ISSUE THREAD

**Issue by BeyondTheStarss** [birsy/Fog-Looks-Good-Now#12]
Hi! I'm running 1.19.2 and have been self hosting a server, me and a friend had been crashing unable to figure out why, as the crash log mentioned create as the cause, but when I went over there they said it was an incompatibility with fog looks good now, So I'm opening this issue in hopes you can fix it, here is the crash log I can provide more info if needed

[crash-2023-03-18_21.29.02-client.txt](https://github.com/birsy/Fog-Looks-Good-Now/files/11012438/crash-2023-03-18_21.29.02-client.txt)

**Comment by birsy** [comment]
This is for the forge version of Fog Looks Good Now - it seems like your crash log for fabric?
