### ISSUE TITLE
1.19.2 Oculus Shaders do not render sun or moon

### ISSUE THREAD

**Issue by FusionSwarly** [birsy/Fog-Looks-Good-Now#14]
While using this mod, Shaders will not render the sun or moon. Works perfectly fine without this mod installed.

Using Complementary Reimagined 2.0.2, Oculus 1.2.8a, Forge 43.2.13

![image](https://github.com/birsy/Fog-Looks-Good-Now/assets/82784004/a378cbcd-26c4-4468-b1d6-6775ea0317f0)

![image](https://github.com/birsy/Fog-Looks-Good-Now/assets/82784004/274306b5-4b5b-4d09-a3cf-cbbe1c9e8a5f)

**Comment by birsy** [comment]
I think I know the issue but there's no real easy way to fix this - shaders generally implement their own controls for fog anyway. Will try to look into this, but I don't think there's much I can do.
