### ISSUE TITLE
[Suggestion] Cave fog should work only under ocean level

### ISSUE THREAD

**Issue by Jukabofy** [birsy/Fog-Looks-Good-Now#5]
![2022-12-22_10 13 17](https://user-images.githubusercontent.com/87483832/209177442-d13ee0f9-f044-4038-bd7b-9c1fcfff54d3.png)
![2022-12-22_10 14 53](https://user-images.githubusercontent.com/87483832/209177504-ed3900f7-ad0f-460f-9785-b50da8b911f1.png)
this thing happens frequently
I think it should possible to restrict the cave fog under a specific y level
I know about caves above y ocean level, if you think about the sky shouldn't be dark even from dark place
this happens too while whatching trought a window inside a close space
So, that's my suggestion soemthing to restrict it

**Comment by birsy** [comment]
fixed in version 1.1!

**Comment by Jukabofy** [comment]
Thank you so much, I'll wait for the next release, I love your mod so much
