### ISSUE TITLE
"Blindness" status effect causes fog to disappear completely

### ISSUE THREAD

**Issue by thimblebird** [birsy/Fog-Looks-Good-Now#7]
without status effect:
![image](https://user-images.githubusercontent.com/93487547/210012787-7938230a-5b21-42f2-ba8d-330157609e1f.png)

with status effect:
![image](https://user-images.githubusercontent.com/93487547/210012800-b7478ab1-053a-43bb-b757-7a82f38605d6.png)

**Comment by birsy** [comment]
fixed in 1.1.1!
